### PR TITLE
Olshansk debugging round2

### PR DESCRIPTION
**Pull request by Olshansk**
Two key changes:

1. Update to the dev container to enable building on an M1 MacBook
2. Instructions on how to connect and read from postgres directly

### CODE REVIEW

**Comment by Olshansk** [comment]
@orgecuesta Please test & review on your machine!

**Comment by jorgecuesta** [comment]
will do on Monday @Olshansk

**Comment by jorgecuesta** [comment]
@Olshansk I replicated your changes to the `production` image and added platform targets to CI to check if this happens again.

**Comment by Olshansk** [comment]
Thanks @jorgecuesta! Going to ship it.

**Pull request merged**
